highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /resume/
title: Irene Teinemaa's Resume
name: Irene Teinemaa
email: irene.teinemaa@gmail.com
email_full: mailto:irene.teinemaa@gmail.com
website: irhete.github.io
website_full: https://irhete.github.io
github: irhete # username
linkedin: ireneteinemaa
googlescholar: UQZ22uQAAAAJ
#tel: +44 0000 000000
#tel_full: tel:+440000000000
google_maps: 'https://www.google.ee/maps/place/Tartu,+Eesti/@58.3768829,26.724445,16z/data=!4m5!3m4!1s0x46eb36d8d55d3df7:0x400b36d18fc6d10!8m2!3d58.377983!4d26.7290383'
address:
#  street: 44 Perth Street
#  postcode: EH3 5BL
  city: Tartu
  country: Estonia
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
