highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: "/resume/"
title: Irene Teinemaa's Resume
name: Irene Teinemaa
email: irene.teinemaa@gmail.com
email_full: mailto:irene.teinemaa@gmail.com
website: irhete.github.io
website_full: https://irhete.github.io
github: irhete # username
linkedin: ireneteinemaa
googlescholar: UQZ22uQAAAAJ
#tel: +44 0000 000000
#tel_full: tel:+440000000000
google_maps: 'https://goo.gl/maps/tRT4viQP4rQDaiKx8'
address:
#  street: 44 Perth Street
#  postcode: EH3 5BL
  city: Amsterdam
  country: The Netherlands
google_analytics: UA-122643272-1

# needed for travis-ci build
exclude: [vendor]
